
package proiectjava.serviceauto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Daria
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPage = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        aboutUs = new javax.swing.JPanel();
        panelMasina1 = new javax.swing.JPanel();
        Masina = new javax.swing.JPanel();
        panelMasina = new javax.swing.JPanel();
        Titlu1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        marcaMasina = new javax.swing.JTextField();
        anFabricatieMasina = new javax.swing.JTextField();
        modelMasina = new javax.swing.JTextField();
        capacitateCilindricaMasina = new javax.swing.JTextField();
        stareMasina = new javax.swing.JTextField();
        pretMasina = new javax.swing.JTextField();
        caroserieMasina = new javax.swing.JTextField();
        categoriePermisMasina = new javax.swing.JTextField();
        seriaMasina = new javax.swing.JTextField();
        butonSalvareMasina = new javax.swing.JButton();
        butonStergeRandMasina = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMasini = new javax.swing.JTable();
        Camion = new javax.swing.JPanel();
        panelCamion = new javax.swing.JPanel();
        Titlu2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        marcaCamion = new javax.swing.JTextField();
        anFabricatieCamion = new javax.swing.JTextField();
        modelCamion = new javax.swing.JTextField();
        capacitateCilindricaCamion = new javax.swing.JTextField();
        capacitateTractareCamion = new javax.swing.JTextField();
        pretCamion = new javax.swing.JTextField();
        categoriePermisCamion = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        stareCamion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelCamioane = new javax.swing.JTable();
        Tractor = new javax.swing.JPanel();
        panelTractor = new javax.swing.JPanel();
        Titlu3 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        marcaTractor = new javax.swing.JTextField();
        anFabricatieTractor = new javax.swing.JTextField();
        modelTractor = new javax.swing.JTextField();
        capacitateCilindricaTractor = new javax.swing.JTextField();
        greutateTractor = new javax.swing.JTextField();
        pretTractor = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        stareTractor = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelTractoare = new javax.swing.JTable();
        Motocicleta = new javax.swing.JPanel();
        panelMotocicleta = new javax.swing.JPanel();
        Titlu4 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        marcaMotocicleta = new javax.swing.JTextField();
        anFabricatieMotocicleta = new javax.swing.JTextField();
        modelMotocicleta = new javax.swing.JTextField();
        capacitateCilindricaMotocicleta = new javax.swing.JTextField();
        stareMotocicleta = new javax.swing.JTextField();
        pretMotocicleta = new javax.swing.JTextField();
        caiPutereMotocicleta = new javax.swing.JTextField();
        culoareMotocicleta = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelMotociclete = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPage.setBackground(new java.awt.Color(216, 214, 196));
        mainPage.setForeground(new java.awt.Color(0, 102, 102));

        logoutButton.setBackground(new java.awt.Color(0, 102, 102));
        logoutButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proiectjava/serviceauto/Dealership_logo_100px.png"))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setForeground(new java.awt.Color(216, 214, 196));

        aboutUs.setBackground(new java.awt.Color(0, 102, 102));
        aboutUs.setForeground(new java.awt.Color(216, 214, 196));

        panelMasina1.setBackground(new java.awt.Color(211, 210, 190));
        panelMasina1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelMasina1Layout = new javax.swing.GroupLayout(panelMasina1);
        panelMasina1.setLayout(panelMasina1Layout);
        panelMasina1Layout.setHorizontalGroup(
            panelMasina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        panelMasina1Layout.setVerticalGroup(
            panelMasina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout aboutUsLayout = new javax.swing.GroupLayout(aboutUs);
        aboutUs.setLayout(aboutUsLayout);
        aboutUsLayout.setHorizontalGroup(
            aboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMasina1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        aboutUsLayout.setVerticalGroup(
            aboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMasina1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Despre noi", aboutUs);

        Masina.setBackground(new java.awt.Color(0, 102, 102));
        Masina.setForeground(new java.awt.Color(211, 210, 190));

        panelMasina.setBackground(new java.awt.Color(211, 210, 190));
        panelMasina.setForeground(new java.awt.Color(0, 0, 0));

        Titlu1.setBackground(new java.awt.Color(211, 210, 190));
        Titlu1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Titlu1.setForeground(new java.awt.Color(0, 0, 0));
        Titlu1.setText("Adauga masina");

        jLabel12.setBackground(new java.awt.Color(211, 210, 190));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Marca");

        jLabel17.setBackground(new java.awt.Color(211, 210, 190));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Model");

        jLabel18.setBackground(new java.awt.Color(211, 210, 190));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Capacitate Cilindrica");

        jLabel19.setBackground(new java.awt.Color(211, 210, 190));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("An Fabricatie");

        jLabel20.setBackground(new java.awt.Color(211, 210, 190));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Pret");

        jLabel21.setBackground(new java.awt.Color(211, 210, 190));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Stare");

        jLabel22.setBackground(new java.awt.Color(211, 210, 190));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Caroserie");

        jLabel23.setBackground(new java.awt.Color(211, 210, 190));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Categorie Permis");

        jLabel24.setBackground(new java.awt.Color(211, 210, 190));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Seria");

        marcaMasina.setBackground(new java.awt.Color(211, 210, 190));
        marcaMasina.setForeground(new java.awt.Color(0, 0, 0));

        anFabricatieMasina.setBackground(new java.awt.Color(211, 210, 190));
        anFabricatieMasina.setForeground(new java.awt.Color(0, 0, 0));

        modelMasina.setBackground(new java.awt.Color(211, 210, 190));
        modelMasina.setForeground(new java.awt.Color(0, 0, 0));

        capacitateCilindricaMasina.setBackground(new java.awt.Color(211, 210, 190));
        capacitateCilindricaMasina.setForeground(new java.awt.Color(0, 0, 0));

        stareMasina.setBackground(new java.awt.Color(211, 210, 190));
        stareMasina.setForeground(new java.awt.Color(0, 0, 0));

        pretMasina.setBackground(new java.awt.Color(211, 210, 190));
        pretMasina.setForeground(new java.awt.Color(0, 0, 0));

        caroserieMasina.setBackground(new java.awt.Color(211, 210, 190));
        caroserieMasina.setForeground(new java.awt.Color(0, 0, 0));

        categoriePermisMasina.setBackground(new java.awt.Color(211, 210, 190));
        categoriePermisMasina.setForeground(new java.awt.Color(0, 0, 0));

        seriaMasina.setBackground(new java.awt.Color(211, 210, 190));
        seriaMasina.setForeground(new java.awt.Color(0, 0, 0));

        butonSalvareMasina.setBackground(new java.awt.Color(0, 0, 0));
        butonSalvareMasina.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        butonSalvareMasina.setForeground(new java.awt.Color(211, 210, 190));
        butonSalvareMasina.setText("SALVEAZA");
        butonSalvareMasina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonSalvareMasinaActionPerformed(evt);
            }
        });

        butonStergeRandMasina.setBackground(new java.awt.Color(0, 0, 0));
        butonStergeRandMasina.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        butonStergeRandMasina.setForeground(new java.awt.Color(211, 210, 190));
        butonStergeRandMasina.setText("STERGE RAND ALES");
        butonStergeRandMasina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonStergeRandMasinaMouseClicked(evt);
            }
        });
        butonStergeRandMasina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonStergeRandMasinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMasinaLayout = new javax.swing.GroupLayout(panelMasina);
        panelMasina.setLayout(panelMasinaLayout);
        panelMasinaLayout.setHorizontalGroup(
            panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMasinaLayout.createSequentialGroup()
                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMasinaLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Titlu1))
                    .addGroup(panelMasinaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMasinaLayout.createSequentialGroup()
                                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(37, 37, 37)
                                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seriaMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoriePermisMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(caroserieMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stareMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anFabricatieMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(marcaMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(capacitateCilindricaMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pretMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelMasinaLayout.createSequentialGroup()
                                .addComponent(butonSalvareMasina)
                                .addGap(18, 18, 18)
                                .addComponent(butonStergeRandMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelMasinaLayout.setVerticalGroup(
            panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMasinaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titlu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(marcaMasina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(modelMasina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(capacitateCilindricaMasina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMasinaLayout.createSequentialGroup()
                        .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMasinaLayout.createSequentialGroup()
                                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(anFabricatieMasina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(pretMasina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(stareMasina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22))
                            .addComponent(caroserieMasina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23))
                    .addComponent(categoriePermisMasina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(seriaMasina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonSalvareMasina)
                    .addComponent(butonStergeRandMasina))
                .addGap(28, 28, 28))
        );

        tabelMasini.setAutoCreateRowSorter(true);
        tabelMasini.setBackground(new java.awt.Color(0, 102, 102));
        tabelMasini.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelMasini.setForeground(new java.awt.Color(216, 214, 196));
        tabelMasini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bmw", "i8", "1599", "2016", "75000", "Fara Accidente", "Cabrio", "B", "WGBRNER124GG"}
            },
            new String [] {
                "Marca", "Model", "Capacitate Cilindrica", "An Fabricatie", "Pret", "Stare", "Caroserie", "Categorie Permis", "Seria"
            }
        ));
        jScrollPane1.setViewportView(tabelMasini);

        javax.swing.GroupLayout MasinaLayout = new javax.swing.GroupLayout(Masina);
        Masina.setLayout(MasinaLayout);
        MasinaLayout.setHorizontalGroup(
            MasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MasinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMasina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MasinaLayout.setVerticalGroup(
            MasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MasinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MasinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMasina, javax.swing.GroupLayout.PREFERRED_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Masina", Masina);

        Camion.setBackground(new java.awt.Color(0, 102, 102));

        panelCamion.setBackground(new java.awt.Color(211, 210, 190));
        panelCamion.setForeground(new java.awt.Color(0, 0, 0));

        Titlu2.setBackground(new java.awt.Color(211, 210, 190));
        Titlu2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Titlu2.setForeground(new java.awt.Color(0, 0, 0));
        Titlu2.setText("Adauga camion");

        jLabel25.setBackground(new java.awt.Color(211, 210, 190));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Marca");

        jLabel26.setBackground(new java.awt.Color(211, 210, 190));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Model");

        jLabel27.setBackground(new java.awt.Color(211, 210, 190));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Capacitate Cilindrica");

        jLabel28.setBackground(new java.awt.Color(211, 210, 190));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("An Fabricatie");

        jLabel29.setBackground(new java.awt.Color(211, 210, 190));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Pret");

        jLabel30.setBackground(new java.awt.Color(211, 210, 190));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Capacitate Tractare");

        jLabel32.setBackground(new java.awt.Color(211, 210, 190));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Categorie Permis");

        marcaCamion.setBackground(new java.awt.Color(211, 210, 190));
        marcaCamion.setForeground(new java.awt.Color(0, 0, 0));

        anFabricatieCamion.setBackground(new java.awt.Color(211, 210, 190));
        anFabricatieCamion.setForeground(new java.awt.Color(0, 0, 0));

        modelCamion.setBackground(new java.awt.Color(211, 210, 190));
        modelCamion.setForeground(new java.awt.Color(0, 0, 0));

        capacitateCilindricaCamion.setBackground(new java.awt.Color(211, 210, 190));
        capacitateCilindricaCamion.setForeground(new java.awt.Color(0, 0, 0));

        capacitateTractareCamion.setBackground(new java.awt.Color(211, 210, 190));
        capacitateTractareCamion.setForeground(new java.awt.Color(0, 0, 0));

        pretCamion.setBackground(new java.awt.Color(211, 210, 190));
        pretCamion.setForeground(new java.awt.Color(0, 0, 0));

        categoriePermisCamion.setBackground(new java.awt.Color(211, 210, 190));
        categoriePermisCamion.setForeground(new java.awt.Color(0, 0, 0));

        jLabel33.setBackground(new java.awt.Color(211, 210, 190));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Stare");

        stareCamion.setBackground(new java.awt.Color(211, 210, 190));
        stareCamion.setForeground(new java.awt.Color(0, 0, 0));

        tabelCamioane.setBackground(new java.awt.Color(0, 102, 102));
        tabelCamioane.setForeground(new java.awt.Color(216, 214, 196));
        tabelCamioane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Model", "Capacitate Cilindrica", "An Fabricatie", "Pret", "Capacitate Tractare", "Categorie Permis", "Stare"
            }
        ));
        jScrollPane2.setViewportView(tabelCamioane);
        if (tabelCamioane.getColumnModel().getColumnCount() > 0) {
            tabelCamioane.getColumnModel().getColumn(5).setHeaderValue("Greutate");
            tabelCamioane.getColumnModel().getColumn(6).setHeaderValue("Categorie Permis");
        }

        javax.swing.GroupLayout panelCamionLayout = new javax.swing.GroupLayout(panelCamion);
        panelCamion.setLayout(panelCamionLayout);
        panelCamionLayout.setHorizontalGroup(
            panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamionLayout.createSequentialGroup()
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCamionLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Titlu2))
                    .addGroup(panelCamionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel30))
                        .addGap(37, 37, 37)
                        .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stareCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacitateTractareCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anFabricatieCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacitateCilindricaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pretCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoriePermisCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCamionLayout.setVerticalGroup(
            panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamionLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titlu2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(marcaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(modelCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(capacitateCilindricaCamion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(anFabricatieCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(pretCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(capacitateTractareCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriePermisCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stareCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout CamionLayout = new javax.swing.GroupLayout(Camion);
        Camion.setLayout(CamionLayout);
        CamionLayout.setHorizontalGroup(
            CamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CamionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCamion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CamionLayout.setVerticalGroup(
            CamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CamionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Camion", Camion);

        Tractor.setBackground(new java.awt.Color(0, 102, 102));

        panelTractor.setBackground(new java.awt.Color(211, 210, 190));
        panelTractor.setForeground(new java.awt.Color(0, 0, 0));

        Titlu3.setBackground(new java.awt.Color(211, 210, 190));
        Titlu3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Titlu3.setForeground(new java.awt.Color(0, 0, 0));
        Titlu3.setText("Adauga tractor");

        jLabel34.setBackground(new java.awt.Color(211, 210, 190));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Marca");

        jLabel35.setBackground(new java.awt.Color(211, 210, 190));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Model");

        jLabel36.setBackground(new java.awt.Color(211, 210, 190));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Capacitate Cilindrica");

        jLabel37.setBackground(new java.awt.Color(211, 210, 190));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("An Fabricatie");

        jLabel38.setBackground(new java.awt.Color(211, 210, 190));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Pret");

        jLabel39.setBackground(new java.awt.Color(211, 210, 190));
        jLabel39.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Stare");

        marcaTractor.setBackground(new java.awt.Color(211, 210, 190));
        marcaTractor.setForeground(new java.awt.Color(0, 0, 0));

        anFabricatieTractor.setBackground(new java.awt.Color(211, 210, 190));
        anFabricatieTractor.setForeground(new java.awt.Color(0, 0, 0));

        modelTractor.setBackground(new java.awt.Color(211, 210, 190));
        modelTractor.setForeground(new java.awt.Color(0, 0, 0));

        capacitateCilindricaTractor.setBackground(new java.awt.Color(211, 210, 190));
        capacitateCilindricaTractor.setForeground(new java.awt.Color(0, 0, 0));

        greutateTractor.setBackground(new java.awt.Color(211, 210, 190));
        greutateTractor.setForeground(new java.awt.Color(0, 0, 0));

        pretTractor.setBackground(new java.awt.Color(211, 210, 190));
        pretTractor.setForeground(new java.awt.Color(0, 0, 0));

        jLabel40.setBackground(new java.awt.Color(211, 210, 190));
        jLabel40.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Greutate");

        stareTractor.setBackground(new java.awt.Color(211, 210, 190));
        stareTractor.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelTractorLayout = new javax.swing.GroupLayout(panelTractor);
        panelTractor.setLayout(panelTractorLayout);
        panelTractorLayout.setHorizontalGroup(
            panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTractorLayout.createSequentialGroup()
                .addGroup(panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTractorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40))
                        .addGap(37, 37, 37)
                        .addGroup(panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(greutateTractor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anFabricatieTractor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcaTractor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelTractor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacitateCilindricaTractor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pretTractor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stareTractor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTractorLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Titlu3)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelTractorLayout.setVerticalGroup(
            panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTractorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titlu3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(marcaTractor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(modelTractor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(capacitateCilindricaTractor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(anFabricatieTractor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(pretTractor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greutateTractor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stareTractor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(161, 161, 161))
        );

        tabelTractoare.setBackground(new java.awt.Color(0, 102, 102));
        tabelTractoare.setForeground(new java.awt.Color(216, 214, 196));
        tabelTractoare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Model", "Capacitate Cilindrica", "An Fabricatie", "Pret", "Greutate", "Stare"
            }
        ));
        jScrollPane3.setViewportView(tabelTractoare);
        if (tabelTractoare.getColumnModel().getColumnCount() > 0) {
            tabelTractoare.getColumnModel().getColumn(5).setHeaderValue("Greutate");
        }

        javax.swing.GroupLayout TractorLayout = new javax.swing.GroupLayout(Tractor);
        Tractor.setLayout(TractorLayout);
        TractorLayout.setHorizontalGroup(
            TractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TractorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTractor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TractorLayout.setVerticalGroup(
            TractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TractorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(panelTractor, javax.swing.GroupLayout.PREFERRED_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tractor", Tractor);

        Motocicleta.setBackground(new java.awt.Color(0, 102, 102));

        panelMotocicleta.setBackground(new java.awt.Color(211, 210, 190));
        panelMotocicleta.setForeground(new java.awt.Color(0, 0, 0));

        Titlu4.setBackground(new java.awt.Color(211, 210, 190));
        Titlu4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Titlu4.setForeground(new java.awt.Color(0, 0, 0));
        Titlu4.setText("Adauga motocicleta");

        jLabel43.setBackground(new java.awt.Color(211, 210, 190));
        jLabel43.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Marca");

        jLabel44.setBackground(new java.awt.Color(211, 210, 190));
        jLabel44.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Model");

        jLabel45.setBackground(new java.awt.Color(211, 210, 190));
        jLabel45.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Capacitate Cilindrica");

        jLabel46.setBackground(new java.awt.Color(211, 210, 190));
        jLabel46.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("An Fabricatie");

        jLabel47.setBackground(new java.awt.Color(211, 210, 190));
        jLabel47.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Pret");

        jLabel48.setBackground(new java.awt.Color(211, 210, 190));
        jLabel48.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Stare");

        jLabel49.setBackground(new java.awt.Color(211, 210, 190));
        jLabel49.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Cai Putere");

        jLabel50.setBackground(new java.awt.Color(211, 210, 190));
        jLabel50.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Culoare");

        marcaMotocicleta.setBackground(new java.awt.Color(211, 210, 190));
        marcaMotocicleta.setForeground(new java.awt.Color(0, 0, 0));

        anFabricatieMotocicleta.setBackground(new java.awt.Color(211, 210, 190));
        anFabricatieMotocicleta.setForeground(new java.awt.Color(0, 0, 0));

        modelMotocicleta.setBackground(new java.awt.Color(211, 210, 190));
        modelMotocicleta.setForeground(new java.awt.Color(0, 0, 0));

        capacitateCilindricaMotocicleta.setBackground(new java.awt.Color(211, 210, 190));
        capacitateCilindricaMotocicleta.setForeground(new java.awt.Color(0, 0, 0));

        stareMotocicleta.setBackground(new java.awt.Color(211, 210, 190));
        stareMotocicleta.setForeground(new java.awt.Color(0, 0, 0));

        pretMotocicleta.setBackground(new java.awt.Color(211, 210, 190));
        pretMotocicleta.setForeground(new java.awt.Color(0, 0, 0));

        caiPutereMotocicleta.setBackground(new java.awt.Color(211, 210, 190));
        caiPutereMotocicleta.setForeground(new java.awt.Color(0, 0, 0));

        culoareMotocicleta.setBackground(new java.awt.Color(211, 210, 190));
        culoareMotocicleta.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelMotocicletaLayout = new javax.swing.GroupLayout(panelMotocicleta);
        panelMotocicleta.setLayout(panelMotocicletaLayout);
        panelMotocicletaLayout.setHorizontalGroup(
            panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotocicletaLayout.createSequentialGroup()
                .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMotocicletaLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Titlu4))
                    .addGroup(panelMotocicletaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50))
                        .addGap(37, 37, 37)
                        .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(culoareMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caiPutereMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stareMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anFabricatieMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcaMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacitateCilindricaMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pretMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelMotocicletaLayout.setVerticalGroup(
            panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotocicletaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titlu4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(marcaMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(modelMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(capacitateCilindricaMotocicleta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMotocicletaLayout.createSequentialGroup()
                        .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMotocicletaLayout.createSequentialGroup()
                                .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel46)
                                    .addComponent(anFabricatieMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel47)
                                    .addComponent(pretMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelMotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel48)
                                    .addComponent(stareMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel49))
                            .addComponent(caiPutereMotocicleta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel50))
                    .addComponent(culoareMotocicleta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );

        tabelMotociclete.setBackground(new java.awt.Color(0, 102, 102));
        tabelMotociclete.setForeground(new java.awt.Color(216, 214, 196));
        tabelMotociclete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Model", "Capacitate Cilindrica", "An Fabricatie", "Pret", "Stare", "Cai Putere", "Culoare"
            }
        ));
        jScrollPane4.setViewportView(tabelMotociclete);

        javax.swing.GroupLayout MotocicletaLayout = new javax.swing.GroupLayout(Motocicleta);
        Motocicleta.setLayout(MotocicletaLayout);
        MotocicletaLayout.setHorizontalGroup(
            MotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MotocicletaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMotocicleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MotocicletaLayout.setVerticalGroup(
            MotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MotocicletaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(panelMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Motocicleta", Motocicleta);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bun venit!");

        javax.swing.GroupLayout mainPageLayout = new javax.swing.GroupLayout(mainPage);
        mainPage.setLayout(mainPageLayout);
        mainPageLayout.setHorizontalGroup(
            mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPageLayout.createSequentialGroup()
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPageLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(separator)
            .addGroup(mainPageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        mainPageLayout.setVerticalGroup(
            mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPageLayout.createSequentialGroup()
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        //de adaugat 
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void butonSalvareMasinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonSalvareMasinaActionPerformed
        // TODO add your handling code here:
        //verificam sa nu fie vreun camp necompletat
        if(marcaMasina.getText().equals("") || modelMasina.getText().equals("") || capacitateCilindricaMasina.getText().equals("") || anFabricatieMasina.getText().equals("") || pretMasina.getText().equals("") || stareMasina.getText().equals("") || caroserieMasina.getText().equals("") || categoriePermisMasina.getText().equals("") || seriaMasina.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Toate campurile sunt obligatorii!");
        }else{
            String date[]={marcaMasina.getText(),modelMasina.getText(),capacitateCilindricaMasina.getText(),anFabricatieMasina.getText(),pretMasina.getText(),stareMasina.getText(),caroserieMasina.getText(),categoriePermisMasina.getText(),seriaMasina.getText()};
            
            DefaultTableModel tblModel=(DefaultTableModel)tabelMasini.getModel();
            
            tblModel.addRow(date);
            JOptionPane.showMessageDialog(this,"Date adaugate cu succes!");
            
            marcaMasina.setText("");
            modelMasina.setText("");
            capacitateCilindricaMasina.setText("");
            anFabricatieMasina.setText("");
            pretMasina.setText("");
            stareMasina.setText("");
            caroserieMasina.setText("");
            categoriePermisMasina.setText("");
            seriaMasina.setText("");
            
            
        }
    }//GEN-LAST:event_butonSalvareMasinaActionPerformed

    private void butonStergeRandMasinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonStergeRandMasinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butonStergeRandMasinaActionPerformed

    private void butonStergeRandMasinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonStergeRandMasinaMouseClicked
        // TODO add your handling code here:
                int column=tabelMasini.getColumnModel().getColumnIndexAtX(evt.getX());
        int row=evt.getY()/tabelMasini.getRowHeight();
        
        if(row<tabelMasini.getRowCount() && row>=0 && column<tabelMasini.getColumnCount() && column>=0){
            Object rowValue=tabelMasini.getValueAt(row,column);
            DefaultTableModel tableModel=(DefaultTableModel)tabelMasini.getModel();
            int[]selectedRows=tabelMasini.getSelectedRows();
            for(int i=0;i<selectedRows.length;i++){
                tableModel.removeRow(selectedRows[i]);
            }
        }
    }//GEN-LAST:event_butonStergeRandMasinaMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Camion;
    private javax.swing.JPanel Masina;
    private javax.swing.JPanel Motocicleta;
    private javax.swing.JLabel Titlu1;
    private javax.swing.JLabel Titlu2;
    private javax.swing.JLabel Titlu3;
    private javax.swing.JLabel Titlu4;
    private javax.swing.JPanel Tractor;
    private javax.swing.JPanel aboutUs;
    private javax.swing.JTextField anFabricatieCamion;
    private javax.swing.JTextField anFabricatieMasina;
    private javax.swing.JTextField anFabricatieMotocicleta;
    private javax.swing.JTextField anFabricatieTractor;
    private javax.swing.JButton butonSalvareMasina;
    private javax.swing.JButton butonStergeRandMasina;
    private javax.swing.JTextField caiPutereMotocicleta;
    private javax.swing.JTextField capacitateCilindricaCamion;
    private javax.swing.JTextField capacitateCilindricaMasina;
    private javax.swing.JTextField capacitateCilindricaMotocicleta;
    private javax.swing.JTextField capacitateCilindricaTractor;
    private javax.swing.JTextField capacitateTractareCamion;
    private javax.swing.JTextField caroserieMasina;
    private javax.swing.JTextField categoriePermisCamion;
    private javax.swing.JTextField categoriePermisMasina;
    private javax.swing.JTextField culoareMotocicleta;
    private javax.swing.JTextField greutateTractor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainPage;
    private javax.swing.JTextField marcaCamion;
    private javax.swing.JTextField marcaMasina;
    private javax.swing.JTextField marcaMotocicleta;
    private javax.swing.JTextField marcaTractor;
    private javax.swing.JTextField modelCamion;
    private javax.swing.JTextField modelMasina;
    private javax.swing.JTextField modelMotocicleta;
    private javax.swing.JTextField modelTractor;
    private javax.swing.JPanel panelCamion;
    private javax.swing.JPanel panelMasina;
    private javax.swing.JPanel panelMasina1;
    private javax.swing.JPanel panelMotocicleta;
    private javax.swing.JPanel panelTractor;
    private javax.swing.JTextField pretCamion;
    private javax.swing.JTextField pretMasina;
    private javax.swing.JTextField pretMotocicleta;
    private javax.swing.JTextField pretTractor;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextField seriaMasina;
    private javax.swing.JTextField stareCamion;
    private javax.swing.JTextField stareMasina;
    private javax.swing.JTextField stareMotocicleta;
    private javax.swing.JTextField stareTractor;
    private javax.swing.JTable tabelCamioane;
    private javax.swing.JTable tabelMasini;
    private javax.swing.JTable tabelMotociclete;
    private javax.swing.JTable tabelTractoare;
    // End of variables declaration//GEN-END:variables

